[project]
name = "The-F.I.R.-v.2"
version = "2.1.1"
description = "Обновление The F.I.R."
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "numpy>=2.4.0",
    "openpyxl>=3.1.5",
    "pandas>=2.3.3",
    "pillow>=12.1.0",
    "pyxlsb>=1.0.10",
]
